---
- name: Create AWS Infrastructure
  hosts: localhost
  connection: local

  tasks:

    - name: Select VM size
      set_fact:
        ec2_actual_size: "{{ tee_shirt_sizes[infra_size] }}"
      vars:
        tee_shirt_sizes: 
          dev: t2.medium
          prod: t2.large
          perf: t2.xlarge

    - name: Including ec2 role for VPC creation
      include_role:
        name: ec2
        tasks_from: ec2_env_setup
      vars:
        ec2_lb_target_port: 8080

    - name: Create Database VM
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Customer: "{{ customer }}"
          Role: database
        ec2_count: 1
        ec2_ami: ami-02ace471
        ec2_size: "{{ ec2_actual_size }}"
        ec2_lb_filters: 
          'tag:Customer': "{{ customer }}"
          'tag:Role': database
          'instance-state-name': [ pending, running ]
  
    - name: Create EAP VMs
      include_role:
        name: ec2
      vars:
        ec2_instance_tags: 
          Customer: "{{ customer }}"
          Role: eap
        ec2_count: "{{ eap_ec2_count }}"
        ec2_ami: ami-0e12cbde3e77cbb98
        ec2_size: "{{ ec2_actual_size }}"
        ec2_lb_filters: 
          'tag:Customer': "{{ customer }}"
          'tag:Role': eap
          'instance-state-name': [ pending, running ]

