- name: Add EAP instances to load balancer
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Include tasks for load balancer control
      include_role:
        name: ec2
        tasks_from: ec2_loadbalancer.yml
      vars:
        ec2_lb_filters:
          "tag:Customer": "{{ customer }}"
          "tag:Role":  eap
          "instance-state-name": running
        ec2_lb_target_port: 8080
