---
# Currently lacking functionality in the DSC resource
- name: Install and Configure MSSQL on Windows hosts
  hosts: all
  tasks:
    - name: Including Windows MSSQL role
      include_role:
        name: win-mssql
        tasks_from: remove.yml
